### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by francoism90**

### CODE REVIEW

**Comment by francoism90** [comment]
@jcfp @Safihre Could you please help me out?

I'm trying to bump the deps, but the build keeps failing, and I don't understand how to solve this.

Thanks

**Comment by Safihre** [comment]
We fix the pytz version in the requirements, is that not used here?

**Comment by francoism90** [comment]
@Safihre Yes, but I'm keep getting a weird error, like it doesn't seem to find the version or the version is a pre-release or something?

**Comment by Safihre** [comment]
No it's a regular release. You could try using an older version, we don't really care about it anyway.

**Comment by francoism90** [comment]
@Safihre I've now used the requirements.txt of the `develop` branch, which seems to work.

Maybe some other dep is causing the issue?

Hopefully it builds, and can be merged. :)

**Pull request merged**
