### PR TITLE
Update cargo-sources.json

### PR DESCRIPTION
**Pull request by MrMinemeet**
Honestly, I just forgot to add the changes in #65

### CODE REVIEW

**Comment by francoism90** [comment]
@MrMinemeet It shouldn't be a problem, as the cargo only needs to bumped, if you also upgrade the manifest (yaml). So you need to update both.

I haven't tested upgrading this lib. I can remember something didn't built after upgrading this to the latest.

**Comment by MrMinemeet** [comment]
It worked locally but I guess I had some mess-up there.

Possibly some build issues depending on the system ([See](https://github.com/pyca/cryptography/pull/11714/commits/59a2df47c4a665590660acbc8793ce9aa88dd2aa))

Currently facing some module not founds, but nothing that cannot be figures out

**Comment by MrMinemeet** [comment]
Currently the build fails as `python3-cryptography` cannot find maturin.
According to a [dependency](https://github.com/pyca/cryptography/issues/12173#issuecomment-2556930421) on their end, they are also blocked.

Tried to get it working but also get stuck in issues with maturin. Probably can be updated in the future when dependencies are sorted out

**Comment by francoism90** [comment]
No worries, I can remember having the same issue or something similar with bumping deps.

Thanks for looking into it. 👍

**Comment by MrMinemeet** [comment]
Honestly I'm not sure as my time is also very limited. So I don't think there is enough benefit

**Pull request closed without merging**
